### PR TITLE
Provide more notes on realtime

### PR DESCRIPTION
**Pull request by rgbkrk**
Follow up to #6

### CODE REVIEW

**Comment by betatim** [comment]
gotta encourage those that write stuff down :memo:

**Comment by rgbkrk** [comment]
I thought we also had some notes _somewhere_ about realtime from chatting with @williamstein. Maybe we left them in hackpad?

**Comment by williamstein** [comment]
Maybe we should chat again...  Incidentally, I spent the last week working on a new sync-friendly [from-scratch react.js-based frontend for Jupyter that will integrate with SMC but looks like Jupyter](https://github.com/sagemathinc/smc/tree/jupyter/src/smc-webapp/jupyter).   
I'm doing this since solid working sync for Jupyter is incredibly important to our customers, and I've failed at getting this to work 100% on top of the existing Jupyter implementation, e.g., due to lack of a stateful backend and other issues. In short, I'm trying to fix [this bug](https://github.com/sagemathinc/smc/issues/1754).

**Comment by williamstein** [comment]
Gees, I should also add that I also spent two very focused weeks recently on a new realtime sync implementation for "basically" JSON documents rather than strings.  This is, of course, critical for structured documents like Jupyter.  This is now in production, and has exactly just enough functionality to handle our structured document types, but not too much.   It's very useful designing something like this based on concrete actual needs (i.e.,  to fix into existing implementations) rather than fantasy.    

This implementation is not documented very well or explained anywhere, but here's [the code](https://github.com/sagemathinc/smc/blob/master/src/smc-util/db-doc.coffee).  The philosophy of how it works is probably a lot more useful than the code -- it really was just a few days to implement on top of other building blocks, once I knew what I needed.  Incidentally, it turns out that using immutable.js was incredibly helpful for this; I did a complete implementation without immutable.js which sucked, so I just deleted that entire thing and started over.

**Comment by williamstein** [comment]
> I thought we also had some notes somewhere about realtime from chatting with @williamstein. Maybe we left them in hackpad?

Maybe https://jupyter.hackpad.com/Real-Time-Collaboration-Notes-nYZaQMst6JL

**Pull request merged**
